---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: volumebackupcontents.kahu.io
spec:
  group: kahu.io
  names:
    kind: VolumeBackupContent
    listKind: VolumeBackupContentList
    plural: volumebackupcontents
    shortNames:
    - vbc
    singular: volumebackupcontent
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    - jsonPath: .spec.backupName
      name: Backup
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: VolumeBackupContent is the Schema for the VolumeBackupContents
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: VolumeBackupContentSpec defines the desired state of VolumeBackupContent
            properties:
              backupName:
                description: BackupName is backup CR name specified during backup
                type: string
              parameters:
                additionalProperties:
                  type: string
                description: Supported volume backup provider information
                type: object
              volumeProvider:
                description: Volume provider for set of volumes
                nullable: true
                type: string
              volumeRef:
                items:
                  properties:
                    csiSnapshot:
                      properties:
                        attribute:
                          additionalProperties:
                            type: string
                          type: object
                        handle:
                          type: string
                        snapshotRef:
                          description: ResourceReference contains enough information
                            to let you inspect or modify the referred kubernetes object.
                          properties:
                            apiVersion:
                              description: API version of the referent.
                              type: string
                            kind:
                              description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                              type: string
                            name:
                              description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                              type: string
                            namespace:
                              description: 'Namespace of the referent. More info:
                                https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/'
                              type: string
                          type: object
                      type: object
                    snapshot:
                      properties:
                        attribute:
                          additionalProperties:
                            type: string
                          type: object
                        handle:
                          type: string
                      type: object
                    volume:
                      description: ResourceReference contains enough information to
                        let you inspect or modify the referred kubernetes object.
                      properties:
                        apiVersion:
                          description: API version of the referent.
                          type: string
                        kind:
                          description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                          type: string
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                          type: string
                        namespace:
                          description: 'Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/'
                          type: string
                      type: object
                  type: object
                type: array
            required:
            - backupName
            type: object
          status:
            description: VolumeBackupContentStatus defines the observed state of VolumeBackupContent
            properties:
              backupState:
                items:
                  properties:
                    backupAttributes:
                      additionalProperties:
                        type: string
                      type: object
                    backupHandle:
                      type: string
                    lastProgressUpdate:
                      format: int64
                      type: integer
                    progress:
                      format: int32
                      type: integer
                    volumeName:
                      type: string
                  type: object
                type: array
              completionTimestamp:
                format: date-time
                nullable: true
                type: string
              failureReason:
                type: string
              phase:
                enum:
                - New
                - InProgress
                - Completed
                - Failed
                - Deleting
                type: string
              startTimestamp:
                format: date-time
                nullable: true
                type: string
              volumeBackupProvider:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
