---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: restores.kahu.io
spec:
  group: kahu.io
  names:
    kind: Restore
    listKind: RestoreList
    plural: restores
    singular: restore
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: Restore is the Schema for the restores API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: RestoreSpec defines the desired state of Restore
            properties:
              backupName:
                description: BackupName is backup CR name specified during backup
                type: string
              excludeNamespaces:
                description: ExcludeNamespaces are set of namespace name should not
                  get considered for restore
                items:
                  type: string
                type: array
              excludeResources:
                description: ExcludeResources are set of kubernetes resource name
                  should not get considered for restore
                items:
                  type: string
                type: array
              includeClusterResource:
                description: IncludeClusterResource is a flag for considering cluster
                  wider resource during restore
                type: boolean
              includeNamespace:
                description: IncludeNamespaces are set of namespaces name considered
                  for restore
                items:
                  type: string
                type: array
              includeResources:
                description: IncludeResources are set of kubernetes resource name
                  considered for restore
                items:
                  type: string
                type: array
              labelSelector:
                description: LabelSelector are label get evaluated against resource
                  selection
                properties:
                  matchExpressions:
                    description: matchExpressions is a list of label selector requirements.
                      The requirements are ANDed.
                    items:
                      description: A label selector requirement is a selector that
                        contains values, a key, and an operator that relates the key
                        and values.
                      properties:
                        key:
                          description: key is the label key that the selector applies
                            to.
                          type: string
                        operator:
                          description: operator represents a key's relationship to
                            a set of values. Valid operators are In, NotIn, Exists
                            and DoesNotExist.
                          type: string
                        values:
                          description: values is an array of string values. If the
                            operator is In or NotIn, the values array must be non-empty.
                            If the operator is Exists or DoesNotExist, the values
                            array must be empty. This array is replaced during a strategic
                            merge patch.
                          items:
                            type: string
                          type: array
                      required:
                      - key
                      - operator
                      type: object
                    type: array
                  matchLabels:
                    additionalProperties:
                      type: string
                    description: matchLabels is a map of {key,value} pairs. A single
                      {key,value} in the matchLabels map is equivalent to an element
                      of matchExpressions, whose key field is "key", the operator
                      is "In", and the values array contains only "value". The requirements
                      are ANDed.
                    type: object
                type: object
              namespaceMapping:
                additionalProperties:
                  type: string
                description: NamespaceMapping is mapping between backed up namespace
                  name against restore namespace name
                type: object
              resourcePrefix:
                description: ResourcePrefix gets prepended in each restored resource
                  name
                type: string
            type: object
          status:
            description: RestoreStatus defines the observed state of Restore
            properties:
              completionTimestamp:
                description: Timestamp is a struct that is equivalent to Time, but
                  intended for protobuf marshalling/unmarshalling. It is generated
                  into a serialization that matches Time. Do not use in Go structs.
                properties:
                  nanos:
                    description: Non-negative fractions of a second at nanosecond
                      resolution. Negative second values with fractions must still
                      have non-negative nanos values that count forward in time. Must
                      be from 0 to 999,999,999 inclusive. This field may be limited
                      in precision depending on context.
                    format: int32
                    type: integer
                  seconds:
                    description: Represents seconds of UTC time since Unix epoch 1970-01-01T00:00:00Z.
                      Must be from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59Z inclusive.
                    format: int64
                    type: integer
                required:
                - nanos
                - seconds
                type: object
              failureReason:
                items:
                  type: string
                type: array
              phase:
                enum:
                - New
                - FailedValidation
                - InProgress
                - Completed
                - PartiallyFailed
                - Failed
                - Deleting
                type: string
              progress:
                description: RestoreProgress expresses overall progress of restore
                properties:
                  itemsRestored:
                    description: ItemsRestored is count of resource got processed
                    type: integer
                  totalItems:
                    description: TotalItems is count of resource to be process
                    type: integer
                type: object
              startTimestamp:
                description: Timestamp is a struct that is equivalent to Time, but
                  intended for protobuf marshalling/unmarshalling. It is generated
                  into a serialization that matches Time. Do not use in Go structs.
                properties:
                  nanos:
                    description: Non-negative fractions of a second at nanosecond
                      resolution. Negative second values with fractions must still
                      have non-negative nanos values that count forward in time. Must
                      be from 0 to 999,999,999 inclusive. This field may be limited
                      in precision depending on context.
                    format: int32
                    type: integer
                  seconds:
                    description: Represents seconds of UTC time since Unix epoch 1970-01-01T00:00:00Z.
                      Must be from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59Z inclusive.
                    format: int64
                    type: integer
                required:
                - nanos
                - seconds
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
